name: flutter_front
description: A Flutter quiz application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.1.0
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_icon.png"
  android_12:
    image: "assets/images/splash_icon.png"
    icon_background_color: "#FFFFFF"
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center 